# Generated by Django 4.2.6 on 2023-10-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_mfd_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
